### PR TITLE
Cleaning up from the semester

### PR DESCRIPTION
**Pull request by djp3**
Created a new pdf that reflects Amanda changes and cleaned up a editting mistake from Meaghan.

### CODE REVIEW

**Comment by djp3** [comment]
Included Meagan's typo corrections

**Review by jaron-burdick — APPROVED** [review]
OK

**Comment by djp3** [comment]
So I think all you need to do is merge this pull request Jaron. -Don

**Comment by djp3** [comment]
So I think all you need to do is merge this pull request Jaron. -Don

**Pull request merged**
